/**
 * Terms of Service Page for AuroraNotes
 * Comprehensive terms covering AI-powered note-taking service
 */

import { memo } from 'react';
import { LegalLayout } from './LegalLayout';

const LAST_UPDATED = 'December 24, 2024';

export const TermsOfService = memo(function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <section className="legal-section">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using AuroraNotes ("Service"), you agree to be bound by these Terms of Service ("Terms"). 
          If you do not agree to these Terms, you may not access or use the Service.
        </p>
        <p>
          These Terms constitute a legally binding agreement between you and AuroraNotes regarding your use of the 
          Service. We may modify these Terms at any time, and such modifications will be effective immediately upon 
          posting. Your continued use of the Service following any modifications indicates your acceptance of the 
          modified Terms.
        </p>
      </section>

      <section className="legal-section">
        <h2>2. Description of Service</h2>
        <p>
          AuroraNotes is an AI-powered note-taking application that allows users to:
        </p>
        <ul>
          <li>Create, edit, organize, and store personal notes</li>
          <li>Ask questions about their notes using natural language and receive AI-generated responses</li>
          <li>Record voice memos and have them transcribed to text using AI</li>
          <li>Search across their notes using semantic and keyword-based search</li>
        </ul>
        <p>
          The Service uses artificial intelligence technologies, including large language models provided by 
          third-party services (Google Gemini/Vertex AI), to power its features.
        </p>
      </section>

      <section className="legal-section">
        <h2>3. Account Registration and Security</h2>
        <p>
          To use the Service, you must create an account using Google Sign-In or phone number verification. 
          You are responsible for:
        </p>
        <ul>
          <li>Maintaining the confidentiality of your account credentials</li>
          <li>All activities that occur under your account</li>
          <li>Notifying us immediately of any unauthorized use of your account</li>
        </ul>
        <p>
          You must be at least 13 years of age to use this Service. If you are under 18, you represent that 
          you have your parent or guardian's permission to use the Service.
        </p>
      </section>

      <section className="legal-section">
        <h2>4. User Content</h2>
        <p>
          "User Content" refers to any notes, text, audio recordings, or other materials you create, upload, 
          or store through the Service. You retain all ownership rights to your User Content.
        </p>
        <p>
          By using the Service, you grant AuroraNotes a limited, non-exclusive license to process your User 
          Content solely for the purpose of providing and improving the Service. This includes:
        </p>
        <ul>
          <li>Storing your notes in our secure database</li>
          <li>Processing your content through AI models to generate responses, transcriptions, and insights</li>
          <li>Creating embeddings and search indexes to enable retrieval features</li>
        </ul>
        <p>
          You are solely responsible for your User Content and represent that you have all necessary rights 
          to grant this license.
        </p>
      </section>

      <section className="legal-section">
        <h2>5. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Store or transmit any content that is unlawful, harmful, threatening, abusive, or otherwise objectionable</li>
          <li>Violate any applicable laws, regulations, or third-party rights</li>
          <li>Attempt to gain unauthorized access to the Service or its related systems</li>
          <li>Interfere with or disrupt the Service or servers connected to the Service</li>
          <li>Use the Service for any commercial purpose without our written consent</li>
          <li>Reverse engineer, decompile, or disassemble any portion of the Service</li>
          <li>Use automated means to access the Service without our permission</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>6. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>Important:</strong> The AI features of the Service, including chat responses, note summaries, 
          action item extraction, and transcriptions, are generated by artificial intelligence systems. 
          These AI-generated outputs:
        </p>
        <ul>
          <li>May contain errors, inaccuracies, or hallucinations</li>
          <li>Should not be relied upon as professional advice (legal, medical, financial, or otherwise)</li>
          <li>Are provided "as is" without any warranty of accuracy or completeness</li>
          <li>May occasionally produce unexpected or inappropriate content</li>
        </ul>
        <p>
          You acknowledge that you are solely responsible for evaluating and verifying any AI-generated 
          content before relying on it. AuroraNotes is not liable for any decisions or actions taken 
          based on AI-generated outputs.
        </p>
      </section>

      <section className="legal-section">
        <h2>7. Voice Recording and Transcription</h2>
        <p>
          When you use the voice recording feature, you consent to:
        </p>
        <ul>
          <li>Your device's microphone being accessed to record audio</li>
          <li>Audio recordings being transmitted to our servers for AI-powered transcription</li>
          <li>Transcribed text being stored as part of your User Content</li>
        </ul>
        <p>
          Audio recordings are processed in real-time and are not permanently stored after transcription 
          is complete unless you choose to save them as notes.
        </p>
      </section>

      <section className="legal-section">
        <h2>8. Intellectual Property</h2>
        <p>
          The Service, including its design, features, content, and underlying technology, is owned by
          AuroraNotes and protected by copyright, trademark, and other intellectual property laws.
          You may not copy, modify, distribute, or create derivative works based on the Service without
          our express written permission.
        </p>
      </section>

      <section className="legal-section">
        <h2>9. Third-Party Services</h2>
        <p>
          The Service relies on third-party services to function, including:
        </p>
        <ul>
          <li><strong>Google Firebase:</strong> For authentication and data storage</li>
          <li><strong>Google Cloud Platform:</strong> For hosting and infrastructure</li>
          <li><strong>Google Gemini/Vertex AI:</strong> For AI-powered features</li>
        </ul>
        <p>
          Your use of the Service is also subject to the terms and policies of these third-party providers.
          We are not responsible for the practices or policies of third-party services.
        </p>
      </section>

      <section className="legal-section">
        <h2>10. Termination</h2>
        <p>
          You may terminate your account at any time by discontinuing use of the Service. We reserve the
          right to suspend or terminate your access to the Service at any time, without prior notice, for
          conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
        </p>
        <p>
          Upon termination, your right to use the Service will immediately cease. Provisions of these Terms
          that by their nature should survive termination will remain in effect.
        </p>
      </section>

      <section className="legal-section">
        <h2>11. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE.
        </p>
        <p>
          We do not warrant that the Service will be uninterrupted, secure, or error-free, that defects
          will be corrected, or that the Service is free of viruses or other harmful components.
        </p>
      </section>

      <section className="legal-section">
        <h2>12. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, AURORANOTES AND ITS AFFILIATES, OFFICERS, DIRECTORS,
          EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL,
          ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
        </p>
        <p>
          IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU EXCEED THE AMOUNT YOU PAID US, IF ANY, FOR USE
          OF THE SERVICE DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
        </p>
      </section>

      <section className="legal-section">
        <h2>13. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless AuroraNotes and its affiliates from and
          against any claims, liabilities, damages, losses, and expenses, including reasonable attorney's
          fees, arising out of or in any way connected with your access to or use of the Service, your
          User Content, or your violation of these Terms.
        </p>
      </section>

      <section className="legal-section">
        <h2>14. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the State of
          Delaware, United States, without regard to its conflict of law provisions. Any disputes arising
          under these Terms shall be resolved exclusively in the state or federal courts located in
          Delaware.
        </p>
      </section>

      <section className="legal-section">
        <h2>15. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify users of material changes
          by posting a notice on our website or through the Service. Your continued use of the Service
          after such modifications constitutes your acceptance of the updated Terms.
        </p>
      </section>

      <section className="legal-section">
        <h2>16. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p className="legal-contact">
          <strong>Email:</strong> legal@auroranotes.app
        </p>
      </section>
    </LegalLayout>
  );
});

